version: '2.18'

services:

  backend_test:
    build: .
    container_name: backend_test
    restart: on-failure
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/parking_information
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: on-failure
    expose:
      - 5432
    environment:
      POSTGRES_DB: "parking_information"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes: 
      - ./init_sql/:/docker-entrypoint-initdb.d/


