version: "3.9"

services:

  backend_test:
    build: .
    container_name: backend_test
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: "parking_information"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes: 
      - ./init_sql/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - mynetwork

   nginx:
    image: nginx
    container_name: nginx
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
    ports:
      - "80:80"
    depends_on:
      - backend_test
    networks:
      - mynetwork


   networks:
      mynetwork:
        driver : bridge
